defaults:
  - dataset: varbinding_dataset
  - model: gpt2_meta_varb
  - _self_

# model & data config will be loaded from defaults

train:
  num_workers: 0
  bsize: 512
  lr: 0.0001
  weight_decay: 1.0
  betas: [0.9, 0.98]
  warmup_steps: 10
  eval_every: 100
  eval_batches: 8
  max_steps: 20000
  grokfast_alpha: 0.98
  grokfast_lamb: 2.0
